name: Create terraform plan

on: [pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate terraform configuration
    env:
      AWS_REGION: ${{ secrets.OBJ_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.OBJ_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.OBJ_SECRET_KEY }}
      AWS_S3_ENDPOINT: ${{ secrets.OBJ_ENDPOINT }}
      TF_VAR_OBJ_BUCKET_URL: ${{ secrets.OBJ_BUCKET_URL }}
      TF_VAR_LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform validate
        uses: dflook/terraform-validate@v1
  fmt-check:
    runs-on: ubuntu-latest
    name: Check formatting of terraform files
    env:
      AWS_REGION: ${{ secrets.OBJ_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.OBJ_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.OBJ_SECRET_KEY }}
      AWS_S3_ENDPOINT: ${{ secrets.OBJ_ENDPOINT }}
      TF_VAR_OBJ_BUCKET_URL: ${{ secrets.OBJ_BUCKET_URL }}
      TF_VAR_LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          backend_config: AWS_REGION=${{ secrets.OBJ_REGION }}
  plan:
    runs-on: ubuntu-latest
    name: Create a plan for an example terraform configuration
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_REGION: ${{ secrets.OBJ_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.OBJ_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.OBJ_SECRET_KEY }}
      AWS_S3_ENDPOINT: ${{ secrets.OBJ_ENDPOINT }}
      TF_VAR_OBJ_BUCKET_URL: ${{ secrets.OBJ_BUCKET_URL }}
      TF_VAR_LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        env:
          AWS_REGION: ${{ secrets.OBJ_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.OBJ_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.OBJ_SECRET_KEY }}
          AWS_S3_ENDPOINT: ${{ secrets.OBJ_ENDPOINT }}
          TF_VAR_OBJ_BUCKET_URL: ${{ secrets.OBJ_BUCKET_URL }}
          TF_VAR_LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}

