name: Apply terraform plan

on:
  push:
    branches:
      - master

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        env:
          TF_VAR_OBJ_REGION: ${{ secrets.OBJ_REGION }}
          TF_VAR_OBJ_ACCESS_KEY: ${{ secrets.OBJ_ACCESS_KEY }}
          TF_VAR_OBJ_SECRET_KEY: ${{ secrets.OBJ_SECRET_KEY }}
          TF_VAR_OBJ_BUCKET_URL: ${{ secrets.OBJ_BUCKET_URL }}
          TF_VAR_LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}

